import type {
  ContractScenario,
  TrainingModuleContent,
} from "../domain/mattershift";

const useCaseId = "ai-assisted-sales-renewal-review";

export const guidedContractScenario: ContractScenario = {
  id: "northstar-sales-renewal-guided",
  mode: "guided",
  useCaseId,
  contractVersion: "1.0",
  contractName: "Northstar Analytics Sales Renewal",
  counterparty: "Northstar Analytics Pte. Ltd.",
  contractValue: 42_000,
  templateVersion: "2026.2",
  clauses: [
    {
      id: "commercial-terms",
      heading: "Commercial terms",
      standardText: "The annual subscription fee is SGD 42,000 for twelve months.",
      submittedText: "The annual subscription fee is SGD 42,000 for twelve months.",
      materiallyChanged: false,
      sourceRefIds: ["approved-template-2026-2", "renewal-routing-playbook"],
    },
    {
      id: "liability",
      heading: "Limitation of liability",
      standardText:
        "Each party's aggregate liability is limited to fees paid in the preceding twelve months, excluding fraud and wilful misconduct.",
      submittedText:
        "Supplier liability is unlimited for all claims, losses and indirect damages arising from the agreement.",
      materiallyChanged: true,
      sourceRefIds: ["approved-template-2026-2", "material-redline-rule"],
    },
    {
      id: "governing-law",
      heading: "Governing law",
      standardText: "This agreement is governed by the laws of Singapore.",
      submittedText: "This agreement is governed by the laws of Singapore.",
      materiallyChanged: false,
      sourceRefIds: ["approved-template-2026-2"],
    },
  ],
  aiFindings: [
    {
      id: "guided-contract-value",
      label: "Contract value",
      field: "contractValue",
      proposedValue: 42_000,
      verifiedValue: 42_000,
      sourceClauseId: "commercial-terms",
      sourceRefIds: ["renewal-routing-playbook"],
      material: true,
    },
    {
      id: "guided-template-version",
      label: "Template version",
      field: "templateVersion",
      proposedValue: "2026.2",
      verifiedValue: "2026.2",
      sourceClauseId: "commercial-terms",
      sourceRefIds: ["approved-template-2026-2"],
      material: true,
    },
    {
      id: "guided-material-redline",
      label: "Material standard-term change",
      field: "materialRedline",
      proposedValue: false,
      verifiedValue: true,
      sourceClauseId: "liability",
      sourceRefIds: ["material-redline-rule", "ai-verification-policy"],
      material: true,
    },
    {
      id: "guided-personal-data",
      label: "Personal data processing",
      field: "personalData",
      proposedValue: false,
      verifiedValue: false,
      sourceClauseId: "commercial-terms",
      sourceRefIds: ["renewal-routing-playbook"],
      material: false,
    },
    {
      id: "guided-governing-law",
      label: "Governing law",
      field: "governingLaw",
      proposedValue: "Singapore",
      verifiedValue: "Singapore",
      sourceClauseId: "governing-law",
      sourceRefIds: ["approved-template-2026-2"],
      material: false,
    },
  ],
  expectedRoute: "legal_review",
};

export const soloReplayContractScenario: ContractScenario = {
  id: "marigold-sales-renewal-solo",
  mode: "solo_replay",
  useCaseId,
  contractVersion: "1.0",
  contractName: "Marigold Systems Sales Renewal",
  counterparty: "Marigold Systems Pte. Ltd.",
  contractValue: 36_000,
  templateVersion: "2026.2",
  clauses: [
    {
      id: "solo-commercial-terms",
      heading: "Commercial terms",
      standardText: "The annual subscription fee is SGD 36,000 for twelve months.",
      submittedText: "The annual subscription fee is SGD 36,000 for twelve months.",
      materiallyChanged: false,
      sourceRefIds: ["approved-template-2026-2", "renewal-routing-playbook"],
    },
    {
      id: "solo-data-processing",
      heading: "Data processing",
      standardText:
        "Customer personal data may be processed only to provide the contracted service in Singapore.",
      submittedText:
        "Customer personal data may be used for product training and transferred to any Supplier location.",
      materiallyChanged: true,
      sourceRefIds: ["approved-template-2026-2", "material-redline-rule"],
    },
    {
      id: "solo-governing-law",
      heading: "Governing law",
      standardText: "This agreement is governed by the laws of Singapore.",
      submittedText: "This agreement is governed by the laws of Singapore.",
      materiallyChanged: false,
      sourceRefIds: ["approved-template-2026-2"],
    },
  ],
  aiFindings: [
    {
      id: "solo-contract-value",
      label: "Contract value",
      field: "contractValue",
      proposedValue: 36_000,
      verifiedValue: 36_000,
      sourceClauseId: "solo-commercial-terms",
      sourceRefIds: ["renewal-routing-playbook"],
      material: true,
    },
    {
      id: "solo-material-redline",
      label: "Material standard-term change",
      field: "materialRedline",
      proposedValue: false,
      verifiedValue: true,
      sourceClauseId: "solo-data-processing",
      sourceRefIds: ["material-redline-rule", "ai-verification-policy"],
      material: true,
    },
    {
      id: "solo-personal-data",
      label: "Personal data processing",
      field: "personalData",
      proposedValue: false,
      verifiedValue: true,
      sourceClauseId: "solo-data-processing",
      sourceRefIds: ["material-redline-rule"],
      material: true,
    },
    {
      id: "solo-template-version",
      label: "Template version",
      field: "templateVersion",
      proposedValue: "2026.2",
      verifiedValue: "2026.2",
      sourceClauseId: "solo-commercial-terms",
      sourceRefIds: ["approved-template-2026-2"],
      material: true,
    },
    {
      id: "solo-governing-law",
      label: "Governing law",
      field: "governingLaw",
      proposedValue: "Singapore",
      verifiedValue: "Singapore",
      sourceClauseId: "solo-governing-law",
      sourceRefIds: ["approved-template-2026-2"],
      material: false,
    },
  ],
  expectedRoute: "legal_review",
};

export const contractTrainingContent: TrainingModuleContent = {
  guidedScenario: guidedContractScenario,
  soloReplayScenario: soloReplayContractScenario,
};
